POST http://localhost:8000/products/create-product
Content-Type: application/json

{
    "name": "Ao Khoac Da Bo",
    "price": 300000,
    "image": "https://product.hstatic.net/1000333546/product/img_3108_a31149fffa5b4617af7aa626ef5922a8_master.jpg",
    "amount": 200
}
###

GET http://localhost:8000/products


###
PATCH http://localhost:8000/products/60d5b032700a8f3a54d722fa
Content-Type: application/json

{
    "name": "Ao Thun",
    "price": 150000,
    "image": "https://product.hstatic.net/1000088324/product/tw009d-t_n1_10f222519d2d4cf4b38a1f343d9b1236_master.png",
    "amount": 500
}

###
DELETE http://localhost:8000/products/60d5eae349747d21fca3ce41
